### ISSUE TITLE
Link youtube

### ISSUE THREAD

**Issue by mundoem3d** [mundoem3d/Freecad-Examples#1]
ALgumas vezes link para o video não funciona

**Comment by Dener-Garcia** [comment]
teste com um dos link abaixo

**Comment by Dener-Garcia** [comment]
https://www.youtube.com/channel/UCTt8-o-ya6n25WtuYTj0hBw

**Comment by Dener-Garcia** [comment]
https://www.youtube.com/watch?v=wUEx0S1Qj_M&list=PLhlu-GBEnLHjYzlPW_i_6QDVEn6lfx4Wa

**Comment by mundoem3d** [comment]
tudo ok
